# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: music_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13music_service.proto\x12\x05music\"\"\n\x0cMusicRequest\x12\x12\n\naudio_path\x18\x01 \x01(\t\">\n\rMusicResponse\x12\r\n\x05genre\x18\x01 \x01(\t\x12\x0f\n\x07\x65motion\x18\x02 \x01(\t\x12\r\n\x05style\x18\x03 \x01(\t2I\n\x0cMusicService\x12\x39\n\x0cPredictGenre\x12\x13.music.MusicRequest\x1a\x14.music.MusicResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MUSICREQUEST']._serialized_start=30
  _globals['_MUSICREQUEST']._serialized_end=64
  _globals['_MUSICRESPONSE']._serialized_start=66
  _globals['_MUSICRESPONSE']._serialized_end=128
  _globals['_MUSICSERVICE']._serialized_start=130
  _globals['_MUSICSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
